/**
 * =============================================================================
 * AI INSIGHT MODEL - AI-Generated Insights & Recommendations
 * =============================================================================
 * 
 * Stores insights, alerts, and recommendations generated by the AI system:
 * - Task reminders
 * - Performance warnings
 * - Attendance anomalies
 * - Productivity suggestions
 * - Team analytics
 * =============================================================================
 */
const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
    const AIInsight = sequelize.define('AIInsight', {
        id: {
            type: DataTypes.UUID,
            defaultValue: DataTypes.UUIDV4,
            primaryKey: true
        },
        company_id: {
            type: DataTypes.UUID,
            allowNull: false
        },
        // Target user (null = company-wide insight)
        user_id: {
            type: DataTypes.UUID,
            allowNull: true
        },
        type: {
            type: DataTypes.ENUM(
                'task_overdue',      // Task past due date
                'task_reminder',     // Upcoming task deadline
                'task_unaccepted',   // Task not accepted
                'performance_low',   // User underperforming
                'performance_high',  // User excelling (positive)
                'attendance_late',   // Late clock-in
                'attendance_absent', // No clock-in
                'attendance_overtime', // Working too many hours
                'team_summary',      // Daily/weekly team summary
                'recommendation'     // General AI recommendation
            ),
            allowNull: false
        },
        severity: {
            type: DataTypes.ENUM('info', 'warning', 'critical', 'positive'),
            defaultValue: 'info'
        },
        title: {
            type: DataTypes.STRING(255),
            allowNull: false
        },
        message: {
            type: DataTypes.TEXT,
            allowNull: false
        },
        // Related entity (task_id, attendance_id, etc.)
        related_entity_type: {
            type: DataTypes.STRING(50),
            allowNull: true
        },
        related_entity_id: {
            type: DataTypes.UUID,
            allowNull: true
        },
        // Metadata for charts/analytics
        metadata: {
            type: DataTypes.JSONB,
            defaultValue: {}
        },
        // Status tracking
        is_read: {
            type: DataTypes.BOOLEAN,
            defaultValue: false
        },
        is_dismissed: {
            type: DataTypes.BOOLEAN,
            defaultValue: false
        },
        is_actioned: {
            type: DataTypes.BOOLEAN,
            defaultValue: false
        },
        // Link to action (e.g., /dashboard/employer/tasks/123)
        action_url: {
            type: DataTypes.STRING,
            allowNull: true
        }
    }, {
        tableName: 'ai_insights',
        timestamps: true,
        underscored: true,
        indexes: [
            { fields: ['company_id', 'is_dismissed'] },
            { fields: ['user_id'] },
            { fields: ['type'] },
            { fields: ['created_at'] }
        ]
    });

    return AIInsight;
};
